### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by KerwinChen** [1024-lab/smart-admin#63]
直接代码 clone 到本地，后端启动报错：
```
15:48:59.039 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Attempted to load Config resource 'class path resource [application.yaml]' via location 'optional:classpath:/' but snakeyaml was not found on the classpath
	at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:47) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:54) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:36) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:108) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:132) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:87) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:116) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.context.config.ConfigDataEnvironment.processInitial(ConfigDataEnvironment.java:240) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:227) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:102) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:94) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:102) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:87) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178) ~[spring-context-5.3.31.jar:5.3.31]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171) ~[spring-context-5.3.31.jar:5.3.31]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) ~[spring-context-5.3.31.jar:5.3.31]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:133) ~[spring-context-5.3.31.jar:5.3.31]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66) ~[spring-boot-2.7.18.jar:2.7.18]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_261]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:344) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.7.18.jar:2.7.18]
	at net.lab1024.sa.admin.AdminApplication.main(AdminApplication.java:38) ~[classes/:?]
已与地址为 ''127.0.0.1:5121'，传输: '套接字'' 的目标虚拟机断开连接

进程已结束，退出代码为 1

```

是不是还需要修改哪里？

**Comment by SinLaber** [comment]
您好，您这个问题怎么解决的？感谢~

**Comment by KerwinChen** [comment]
> 您好，您这个问题怎么解决的？感谢~

重启 idea 就好了。。

**Comment by SinLaber** [comment]
启动了，无语了哈哈哈哈哈哈，感谢~
---- 回复的原邮件 ----
发件人Chen ***@***.***>发送日期2025年4月8日 ***@***.***>抄送人Bin ***@***.***>,
***@***.***>主题Re: [1024-lab/smart-admin] 启动报错 (Issue #63)
您好，您这个问题怎么解决的？感谢~
重启 idea 就好了。。
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>
KerwinChen left a comment (1024-lab/smart-admin#63)
您好，您这个问题怎么解决的？感谢~
重启 idea 就好了。。
